/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AggregatedEntry {
  'date' : bigint,
  'mood' : [] | [Mood],
  'sober' : boolean,
  'checkInCount' : bigint,
  'drinks' : bigint,
}
export interface CheckInEntry {
  'date' : bigint,
  'mood' : [] | [Mood],
  'sober' : boolean,
  'drinks' : bigint,
}
export interface DayCheckInResponse {
  'date' : bigint,
  'message' : string,
  'totalDrinks' : bigint,
  'feedbackMatrixEntry' : FeedbackMatrixEntry,
  'isFollowUp' : boolean,
}
export interface DayCheckinStatus {
  '_firstCheckTime' : [] | [bigint],
  'hasCheckedIn' : boolean,
  'numberOfChecks' : bigint,
  'drinks' : bigint,
}
export type DrinkingBaseline = { 'low' : null } |
  { 'high' : null } |
  { 'avoidant' : null } |
  { 'medium' : null };
export interface FeedbackMatrixEntry {
  'secondarySubstance' : [] | [string],
  'baselineTier' : DrinkingBaseline,
  'isWeekend' : [] | [boolean],
  'ageRange' : string,
  'daysUntilFullMoon' : [] | [bigint],
  'streakRatio' : [] | [string],
  'message' : string,
  'motivation' : MotivationLens,
  'chanceOfDrinkingTomorrow' : [] | [string],
}
export type Mood = { 'sad' : null } |
  { 'happy' : null } |
  { 'neutral' : null };
export type MotivationLens = { 'sex' : null } |
  { 'money' : null } |
  { 'sport' : null } |
  { 'family' : null } |
  { 'health' : null };
export interface OnboardingAnswers {
  'drinksPerWeek' : string,
  'secondarySubstance' : [] | [string],
  'baselineTier' : DrinkingBaseline,
  'sobrietyDuration' : string,
  'ageRange' : string,
  'motivation' : MotivationLens,
  'timeZone' : string,
}
export interface UserProfile {
  'lastCheckInDate' : [] | [bigint],
  'onboardingAnswers' : OnboardingAnswers,
  'currentDayCheckInStatus' : [] | [DayCheckinStatus],
  'hasCompletedOnboarding' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFeedbackMatrixEntry' : ActorMethod<[FeedbackMatrixEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkOnboardingAndCheckInStatus' : ActorMethod<
    [],
    {
      'needsDailyCheckIn' : boolean,
      'isFirstLoginOfDay' : boolean,
      'isDailyCheckInCompleted' : boolean,
      'needsOnboarding' : boolean,
      'lastLoginWasSober' : bigint,
      'soberDaysTarget' : bigint,
      'needsFollowUp' : boolean,
    }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLast14Days' : ActorMethod<[], Array<AggregatedEntry>>,
  'getLatestBrutalFriendFeedback' : ActorMethod<[], string>,
  'getMoodTrend' : ActorMethod<[], bigint>,
  'getMotivationMessage' : ActorMethod<
    [],
    {
      'remainingClicks' : bigint,
      'message' : string,
      'isLimitReached' : boolean,
    }
  >,
  'getProgressMetrics' : ActorMethod<
    [],
    {
      'last14Days' : Array<AggregatedEntry>,
      'drankDays' : bigint,
      'soberDays' : bigint,
      'totalCheckIns' : bigint,
      'currentStreak' : bigint,
    }
  >,
  'getSoberDaysTarget' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserTimeZone' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCheckIn' : ActorMethod<[CheckInEntry], DayCheckInResponse>,
  'submitFollowUpCheckIn' : ActorMethod<[bigint], DayCheckInResponse>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];