/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DrinkingBaseline = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'avoidant' : IDL.Null,
  'medium' : IDL.Null,
});
export const MotivationLens = IDL.Variant({
  'sex' : IDL.Null,
  'money' : IDL.Null,
  'sport' : IDL.Null,
  'family' : IDL.Null,
  'health' : IDL.Null,
});
export const FeedbackMatrixEntry = IDL.Record({
  'secondarySubstance' : IDL.Opt(IDL.Text),
  'baselineTier' : DrinkingBaseline,
  'isWeekend' : IDL.Opt(IDL.Bool),
  'ageRange' : IDL.Text,
  'daysUntilFullMoon' : IDL.Opt(IDL.Nat),
  'streakRatio' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'motivation' : MotivationLens,
  'chanceOfDrinkingTomorrow' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OnboardingAnswers = IDL.Record({
  'drinksPerWeek' : IDL.Text,
  'secondarySubstance' : IDL.Opt(IDL.Text),
  'baselineTier' : DrinkingBaseline,
  'sobrietyDuration' : IDL.Text,
  'ageRange' : IDL.Text,
  'motivation' : MotivationLens,
  'timeZone' : IDL.Text,
});
export const DayCheckinStatus = IDL.Record({
  '_firstCheckTime' : IDL.Opt(IDL.Nat64),
  'hasCheckedIn' : IDL.Bool,
  'numberOfChecks' : IDL.Nat,
  'drinks' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'lastCheckInDate' : IDL.Opt(IDL.Nat64),
  'onboardingAnswers' : OnboardingAnswers,
  'currentDayCheckInStatus' : IDL.Opt(DayCheckinStatus),
  'hasCompletedOnboarding' : IDL.Bool,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'neutral' : IDL.Null,
});
export const AggregatedEntry = IDL.Record({
  'date' : IDL.Nat64,
  'mood' : IDL.Opt(Mood),
  'sober' : IDL.Bool,
  'checkInCount' : IDL.Nat,
  'drinks' : IDL.Nat,
});
export const CheckInEntry = IDL.Record({
  'date' : IDL.Nat64,
  'mood' : IDL.Opt(Mood),
  'sober' : IDL.Bool,
  'drinks' : IDL.Nat,
});
export const DayCheckInResponse = IDL.Record({
  'date' : IDL.Nat64,
  'message' : IDL.Text,
  'totalDrinks' : IDL.Nat,
  'feedbackMatrixEntry' : FeedbackMatrixEntry,
  'isFollowUp' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFeedbackMatrixEntry' : IDL.Func([FeedbackMatrixEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkOnboardingAndCheckInStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'needsDailyCheckIn' : IDL.Bool,
          'isFirstLoginOfDay' : IDL.Bool,
          'isDailyCheckInCompleted' : IDL.Bool,
          'needsOnboarding' : IDL.Bool,
          'lastLoginWasSober' : IDL.Int,
          'soberDaysTarget' : IDL.Nat,
          'needsFollowUp' : IDL.Bool,
        }),
      ],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLast14Days' : IDL.Func([], [IDL.Vec(AggregatedEntry)], ['query']),
  'getLatestBrutalFriendFeedback' : IDL.Func([], [IDL.Text], ['query']),
  'getMoodTrend' : IDL.Func([], [IDL.Nat], ['query']),
  'getMotivationMessage' : IDL.Func(
      [],
      [
        IDL.Record({
          'remainingClicks' : IDL.Nat,
          'message' : IDL.Text,
          'isLimitReached' : IDL.Bool,
        }),
      ],
      [],
    ),
  'getProgressMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'last14Days' : IDL.Vec(AggregatedEntry),
          'drankDays' : IDL.Nat,
          'soberDays' : IDL.Nat,
          'totalCheckIns' : IDL.Nat,
          'currentStreak' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getSoberDaysTarget' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserTimeZone' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCheckIn' : IDL.Func([CheckInEntry], [DayCheckInResponse], []),
  'submitFollowUpCheckIn' : IDL.Func([IDL.Nat], [DayCheckInResponse], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DrinkingBaseline = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'avoidant' : IDL.Null,
    'medium' : IDL.Null,
  });
  const MotivationLens = IDL.Variant({
    'sex' : IDL.Null,
    'money' : IDL.Null,
    'sport' : IDL.Null,
    'family' : IDL.Null,
    'health' : IDL.Null,
  });
  const FeedbackMatrixEntry = IDL.Record({
    'secondarySubstance' : IDL.Opt(IDL.Text),
    'baselineTier' : DrinkingBaseline,
    'isWeekend' : IDL.Opt(IDL.Bool),
    'ageRange' : IDL.Text,
    'daysUntilFullMoon' : IDL.Opt(IDL.Nat),
    'streakRatio' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'motivation' : MotivationLens,
    'chanceOfDrinkingTomorrow' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OnboardingAnswers = IDL.Record({
    'drinksPerWeek' : IDL.Text,
    'secondarySubstance' : IDL.Opt(IDL.Text),
    'baselineTier' : DrinkingBaseline,
    'sobrietyDuration' : IDL.Text,
    'ageRange' : IDL.Text,
    'motivation' : MotivationLens,
    'timeZone' : IDL.Text,
  });
  const DayCheckinStatus = IDL.Record({
    '_firstCheckTime' : IDL.Opt(IDL.Nat64),
    'hasCheckedIn' : IDL.Bool,
    'numberOfChecks' : IDL.Nat,
    'drinks' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'lastCheckInDate' : IDL.Opt(IDL.Nat64),
    'onboardingAnswers' : OnboardingAnswers,
    'currentDayCheckInStatus' : IDL.Opt(DayCheckinStatus),
    'hasCompletedOnboarding' : IDL.Bool,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const AggregatedEntry = IDL.Record({
    'date' : IDL.Nat64,
    'mood' : IDL.Opt(Mood),
    'sober' : IDL.Bool,
    'checkInCount' : IDL.Nat,
    'drinks' : IDL.Nat,
  });
  const CheckInEntry = IDL.Record({
    'date' : IDL.Nat64,
    'mood' : IDL.Opt(Mood),
    'sober' : IDL.Bool,
    'drinks' : IDL.Nat,
  });
  const DayCheckInResponse = IDL.Record({
    'date' : IDL.Nat64,
    'message' : IDL.Text,
    'totalDrinks' : IDL.Nat,
    'feedbackMatrixEntry' : FeedbackMatrixEntry,
    'isFollowUp' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFeedbackMatrixEntry' : IDL.Func([FeedbackMatrixEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkOnboardingAndCheckInStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'needsDailyCheckIn' : IDL.Bool,
            'isFirstLoginOfDay' : IDL.Bool,
            'isDailyCheckInCompleted' : IDL.Bool,
            'needsOnboarding' : IDL.Bool,
            'lastLoginWasSober' : IDL.Int,
            'soberDaysTarget' : IDL.Nat,
            'needsFollowUp' : IDL.Bool,
          }),
        ],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLast14Days' : IDL.Func([], [IDL.Vec(AggregatedEntry)], ['query']),
    'getLatestBrutalFriendFeedback' : IDL.Func([], [IDL.Text], ['query']),
    'getMoodTrend' : IDL.Func([], [IDL.Nat], ['query']),
    'getMotivationMessage' : IDL.Func(
        [],
        [
          IDL.Record({
            'remainingClicks' : IDL.Nat,
            'message' : IDL.Text,
            'isLimitReached' : IDL.Bool,
          }),
        ],
        [],
      ),
    'getProgressMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'last14Days' : IDL.Vec(AggregatedEntry),
            'drankDays' : IDL.Nat,
            'soberDays' : IDL.Nat,
            'totalCheckIns' : IDL.Nat,
            'currentStreak' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getSoberDaysTarget' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserTimeZone' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCheckIn' : IDL.Func([CheckInEntry], [DayCheckInResponse], []),
    'submitFollowUpCheckIn' : IDL.Func([IDL.Nat], [DayCheckInResponse], []),
  });
};

export const init = ({ IDL }) => { return []; };