/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Mood = IDL.Variant({
  'sad' : IDL.Null,
  'happy' : IDL.Null,
  'neutral' : IDL.Null,
});
export const AggregatedEntry = IDL.Record({
  'date' : IDL.Nat64,
  'mood' : IDL.Opt(Mood),
  'sober' : IDL.Bool,
  'checkInCount' : IDL.Nat,
  'drinks' : IDL.Nat,
});
export const OnboardingAnswers = IDL.Record({
  'drinksPerWeek' : IDL.Text,
  'secondarySubstance' : IDL.Text,
  'sobrietyDuration' : IDL.Text,
  'ageRange' : IDL.Text,
  'motivation' : IDL.Text,
  'timeZone' : IDL.Text,
});
export const RepeatCheckInReason = IDL.Variant({
  'habit' : IDL.Null,
  'urge' : IDL.Null,
  'curiosity' : IDL.Null,
  'bored' : IDL.Null,
  'reflection' : IDL.Null,
});
export const RepeatCheckIn = IDL.Record({
  'timestamp' : IDL.Nat64,
  'reason' : RepeatCheckInReason,
});
export const PersistentUserProfileView = IDL.Record({
  'lastCheckInDate' : IDL.Opt(IDL.Nat64),
  'aggregatedEntries' : IDL.Vec(AggregatedEntry),
  'lastMotivationClickDay' : IDL.Nat64,
  'motivationButtonClicks' : IDL.Nat,
  'onboardingAnswers' : OnboardingAnswers,
  'lastBrutalFriendFeedback' : IDL.Text,
  'repeatCheckIns' : IDL.Vec(RepeatCheckIn),
  'currentDayCheckInStatus' : IDL.Opt(IDL.Bool),
  'hasCompletedOnboarding' : IDL.Bool,
  'currentDayTotalDrinks' : IDL.Nat,
});
export const CheckInEntry = IDL.Record({
  'date' : IDL.Nat64,
  'mood' : IDL.Opt(Mood),
  'sober' : IDL.Bool,
  'drinks' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkOnboardingAndCheckInStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'needsDailyCheckIn' : IDL.Bool,
          'isFirstLoginOfDay' : IDL.Bool,
          'isDailyCheckInCompleted' : IDL.Bool,
          'needsOnboarding' : IDL.Bool,
          'dailyCheckInsToday' : IDL.Nat,
          'lastLoginWasSober' : IDL.Int,
          'needsFollowUp' : IDL.Bool,
        }),
      ],
      [],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(PersistentUserProfileView)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLast14Days' : IDL.Func([], [IDL.Vec(AggregatedEntry)], ['query']),
  'getLatestBrutalFriendFeedback' : IDL.Func([], [IDL.Text], ['query']),
  'getMoodTrend' : IDL.Func([], [IDL.Nat], ['query']),
  'getMotivationMessage' : IDL.Func(
      [],
      [
        IDL.Record({
          'remainingClicks' : IDL.Nat,
          'message' : IDL.Text,
          'isLimitReached' : IDL.Bool,
        }),
      ],
      [],
    ),
  'getProgressMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'last14Days' : IDL.Vec(AggregatedEntry),
          'drankDays' : IDL.Nat,
          'soberDays' : IDL.Nat,
          'totalCheckIns' : IDL.Nat,
          'currentStreak' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PersistentUserProfileView)],
      ['query'],
    ),
  'getUserTimeZone' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([PersistentUserProfileView], [], []),
  'submitCheckIn' : IDL.Func(
      [CheckInEntry],
      [
        IDL.Record({
          'date' : IDL.Nat64,
          'message' : IDL.Text,
          'totalDrinks' : IDL.Nat,
        }),
      ],
      [],
    ),
  'submitFollowUpCheckIn' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'submitRepeatCheckIn' : IDL.Func([RepeatCheckInReason], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Mood = IDL.Variant({
    'sad' : IDL.Null,
    'happy' : IDL.Null,
    'neutral' : IDL.Null,
  });
  const AggregatedEntry = IDL.Record({
    'date' : IDL.Nat64,
    'mood' : IDL.Opt(Mood),
    'sober' : IDL.Bool,
    'checkInCount' : IDL.Nat,
    'drinks' : IDL.Nat,
  });
  const OnboardingAnswers = IDL.Record({
    'drinksPerWeek' : IDL.Text,
    'secondarySubstance' : IDL.Text,
    'sobrietyDuration' : IDL.Text,
    'ageRange' : IDL.Text,
    'motivation' : IDL.Text,
    'timeZone' : IDL.Text,
  });
  const RepeatCheckInReason = IDL.Variant({
    'habit' : IDL.Null,
    'urge' : IDL.Null,
    'curiosity' : IDL.Null,
    'bored' : IDL.Null,
    'reflection' : IDL.Null,
  });
  const RepeatCheckIn = IDL.Record({
    'timestamp' : IDL.Nat64,
    'reason' : RepeatCheckInReason,
  });
  const PersistentUserProfileView = IDL.Record({
    'lastCheckInDate' : IDL.Opt(IDL.Nat64),
    'aggregatedEntries' : IDL.Vec(AggregatedEntry),
    'lastMotivationClickDay' : IDL.Nat64,
    'motivationButtonClicks' : IDL.Nat,
    'onboardingAnswers' : OnboardingAnswers,
    'lastBrutalFriendFeedback' : IDL.Text,
    'repeatCheckIns' : IDL.Vec(RepeatCheckIn),
    'currentDayCheckInStatus' : IDL.Opt(IDL.Bool),
    'hasCompletedOnboarding' : IDL.Bool,
    'currentDayTotalDrinks' : IDL.Nat,
  });
  const CheckInEntry = IDL.Record({
    'date' : IDL.Nat64,
    'mood' : IDL.Opt(Mood),
    'sober' : IDL.Bool,
    'drinks' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkOnboardingAndCheckInStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'needsDailyCheckIn' : IDL.Bool,
            'isFirstLoginOfDay' : IDL.Bool,
            'isDailyCheckInCompleted' : IDL.Bool,
            'needsOnboarding' : IDL.Bool,
            'dailyCheckInsToday' : IDL.Nat,
            'lastLoginWasSober' : IDL.Int,
            'needsFollowUp' : IDL.Bool,
          }),
        ],
        [],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(PersistentUserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLast14Days' : IDL.Func([], [IDL.Vec(AggregatedEntry)], ['query']),
    'getLatestBrutalFriendFeedback' : IDL.Func([], [IDL.Text], ['query']),
    'getMoodTrend' : IDL.Func([], [IDL.Nat], ['query']),
    'getMotivationMessage' : IDL.Func(
        [],
        [
          IDL.Record({
            'remainingClicks' : IDL.Nat,
            'message' : IDL.Text,
            'isLimitReached' : IDL.Bool,
          }),
        ],
        [],
      ),
    'getProgressMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'last14Days' : IDL.Vec(AggregatedEntry),
            'drankDays' : IDL.Nat,
            'soberDays' : IDL.Nat,
            'totalCheckIns' : IDL.Nat,
            'currentStreak' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PersistentUserProfileView)],
        ['query'],
      ),
    'getUserTimeZone' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([PersistentUserProfileView], [], []),
    'submitCheckIn' : IDL.Func(
        [CheckInEntry],
        [
          IDL.Record({
            'date' : IDL.Nat64,
            'message' : IDL.Text,
            'totalDrinks' : IDL.Nat,
          }),
        ],
        [],
      ),
    'submitFollowUpCheckIn' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'submitRepeatCheckIn' : IDL.Func([RepeatCheckInReason], [], []),
  });
};

export const init = ({ IDL }) => { return []; };