/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AggregatedEntry {
    date: bigint;
    mood?: Mood;
    sober: boolean;
    checkInCount: bigint;
    drinks: bigint;
}
export interface CheckInEntry {
    date: bigint;
    mood?: Mood;
    sober: boolean;
    drinks: bigint;
}
export interface UserProfile {
    lastCheckInDate?: bigint;
    onboardingAnswers: OnboardingAnswers;
    currentDayCheckInStatus?: boolean;
    hasCompletedOnboarding: boolean;
}
export interface OnboardingAnswers {
    drinksPerWeek: string;
    secondarySubstance: string;
    sobrietyDuration: string;
    ageRange: string;
    motivation: string;
    timeZone: string;
}
export enum Mood {
    sad = "sad",
    happy = "happy",
    neutral = "neutral"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkOnboardingAndCheckInStatus(): Promise<{
        needsDailyCheckIn: boolean;
        isFirstLoginOfDay: boolean;
        isDailyCheckInCompleted: boolean;
        needsOnboarding: boolean;
        lastLoginWasSober: bigint;
        needsFollowUp: boolean;
    }>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLast14Days(): Promise<Array<AggregatedEntry>>;
    getLatestBrutalFriendFeedback(): Promise<string>;
    getMoodTrend(): Promise<bigint>;
    getMotivationMessage(): Promise<{
        remainingClicks: bigint;
        message: string;
        isLimitReached: boolean;
    }>;
    getProgressMetrics(): Promise<{
        last14Days: Array<AggregatedEntry>;
        drankDays: bigint;
        soberDays: bigint;
        totalCheckIns: bigint;
        currentStreak: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserTimeZone(): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitCheckIn(entry: CheckInEntry): Promise<{
        date: bigint;
        message: string;
        totalDrinks: bigint;
    }>;
    submitFollowUpCheckIn(drinks: bigint): Promise<string>;
}
import type { AggregatedEntry as _AggregatedEntry, CheckInEntry as _CheckInEntry, Mood as _Mood, OnboardingAnswers as _OnboardingAnswers, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkOnboardingAndCheckInStatus(): Promise<{
        needsDailyCheckIn: boolean;
        isFirstLoginOfDay: boolean;
        isDailyCheckInCompleted: boolean;
        needsOnboarding: boolean;
        lastLoginWasSober: bigint;
        needsFollowUp: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOnboardingAndCheckInStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOnboardingAndCheckInStatus();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLast14Days(): Promise<Array<AggregatedEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLast14Days();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLast14Days();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestBrutalFriendFeedback(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestBrutalFriendFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestBrutalFriendFeedback();
            return result;
        }
    }
    async getMoodTrend(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMoodTrend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMoodTrend();
            return result;
        }
    }
    async getMotivationMessage(): Promise<{
        remainingClicks: bigint;
        message: string;
        isLimitReached: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMotivationMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMotivationMessage();
            return result;
        }
    }
    async getProgressMetrics(): Promise<{
        last14Days: Array<AggregatedEntry>;
        drankDays: bigint;
        soberDays: bigint;
        totalCheckIns: bigint;
        currentStreak: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProgressMetrics();
                return from_candid_record_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProgressMetrics();
            return from_candid_record_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTimeZone(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTimeZone();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTimeZone();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitCheckIn(arg0: CheckInEntry): Promise<{
        date: bigint;
        message: string;
        totalDrinks: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCheckIn(to_candid_CheckInEntry_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCheckIn(to_candid_CheckInEntry_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitFollowUpCheckIn(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFollowUpCheckIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFollowUpCheckIn(arg0);
            return result;
        }
    }
}
function from_candid_AggregatedEntry_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AggregatedEntry): AggregatedEntry {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Mood_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Mood): Mood {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Mood]): Mood | null {
    return value.length === 0 ? null : from_candid_Mood_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: bigint;
    mood: [] | [_Mood];
    sober: boolean;
    checkInCount: bigint;
    drinks: bigint;
}): {
    date: bigint;
    mood?: Mood;
    sober: boolean;
    checkInCount: bigint;
    drinks: bigint;
} {
    return {
        date: value.date,
        mood: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.mood)),
        sober: value.sober,
        checkInCount: value.checkInCount,
        drinks: value.drinks
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    last14Days: Array<_AggregatedEntry>;
    drankDays: bigint;
    soberDays: bigint;
    totalCheckIns: bigint;
    currentStreak: bigint;
}): {
    last14Days: Array<AggregatedEntry>;
    drankDays: bigint;
    soberDays: bigint;
    totalCheckIns: bigint;
    currentStreak: bigint;
} {
    return {
        last14Days: from_candid_vec_n10(_uploadFile, _downloadFile, value.last14Days),
        drankDays: value.drankDays,
        soberDays: value.soberDays,
        totalCheckIns: value.totalCheckIns,
        currentStreak: value.currentStreak
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastCheckInDate: [] | [bigint];
    onboardingAnswers: _OnboardingAnswers;
    currentDayCheckInStatus: [] | [boolean];
    hasCompletedOnboarding: boolean;
}): {
    lastCheckInDate?: bigint;
    onboardingAnswers: OnboardingAnswers;
    currentDayCheckInStatus?: boolean;
    hasCompletedOnboarding: boolean;
} {
    return {
        lastCheckInDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.lastCheckInDate)),
        onboardingAnswers: value.onboardingAnswers,
        currentDayCheckInStatus: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.currentDayCheckInStatus)),
        hasCompletedOnboarding: value.hasCompletedOnboarding
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    happy: null;
} | {
    neutral: null;
}): Mood {
    return "sad" in value ? Mood.sad : "happy" in value ? Mood.happy : "neutral" in value ? Mood.neutral : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AggregatedEntry>): Array<AggregatedEntry> {
    return value.map((x)=>from_candid_AggregatedEntry_n11(_uploadFile, _downloadFile, x));
}
function to_candid_CheckInEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckInEntry): _CheckInEntry {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Mood_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): _Mood {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastCheckInDate?: bigint;
    onboardingAnswers: OnboardingAnswers;
    currentDayCheckInStatus?: boolean;
    hasCompletedOnboarding: boolean;
}): {
    lastCheckInDate: [] | [bigint];
    onboardingAnswers: _OnboardingAnswers;
    currentDayCheckInStatus: [] | [boolean];
    hasCompletedOnboarding: boolean;
} {
    return {
        lastCheckInDate: value.lastCheckInDate ? candid_some(value.lastCheckInDate) : candid_none(),
        onboardingAnswers: value.onboardingAnswers,
        currentDayCheckInStatus: value.currentDayCheckInStatus ? candid_some(value.currentDayCheckInStatus) : candid_none(),
        hasCompletedOnboarding: value.hasCompletedOnboarding
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: bigint;
    mood?: Mood;
    sober: boolean;
    drinks: bigint;
}): {
    date: bigint;
    mood: [] | [_Mood];
    sober: boolean;
    drinks: bigint;
} {
    return {
        date: value.date,
        mood: value.mood ? candid_some(to_candid_Mood_n21(_uploadFile, _downloadFile, value.mood)) : candid_none(),
        sober: value.sober,
        drinks: value.drinks
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Mood): {
    sad: null;
} | {
    happy: null;
} | {
    neutral: null;
} {
    return value == Mood.sad ? {
        sad: null
    } : value == Mood.happy ? {
        happy: null
    } : value == Mood.neutral ? {
        neutral: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
